LOCK TABLES `AB_testkcs` WRITE;
INSERT INTO `AB_testkcs` (
  `uuid`,
  `created_at`,
  `updated_at`,
  `properties`,
  `testkcsid`,
  `singlelinetext`,
  `singlelinetextrequired`,
  `longtext`,
  `longtextrequired`,
  `number`,
  `numberrequired`,
  `numberunique`,
  `numberformatdecimalsthousands`,
  `numbervalidation`,
  `date`,
  `daterequired`,
  `datetime`,
  `datetimerequired`,
  `time`,
  `checkbox`,
  `checkboxrequired`,
  `selectlist`,
  `selectlistrequired`,
  `selectlistmultiselect`,
  `selectlistmultiselectrequired`,
  `email`,
  `emailrequired`
)
VALUES (
  UUID(),
  NOW(),
  NOW(),
  "text",
  "10",
  "text",
  "text",
  "longtext",
  "longtext",
  "11",
  "22",
  "33",
  "1.9",
  "5",
  NOW(),
  NOW(),
  NOW(),
  NOW(),
  NOW(),
  "0",
  "1",
  "item2",
  "item3",
  "[{\"id\":\"item4\",\"text\":\"item4\",\"hex\":\"#673AB7\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item4\"}]},{\"id\":\"item5\",\"text\":\"item5\",\"hex\":\"#3F51B5\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item5\"}]}]",
  "[{\"id\":\"item1\",\"text\":\"item1\",\"hex\":\"#F44336\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item1\"}]},{\"id\":\"item2\",\"text\":\"item2\",\"hex\":\"#E91E63\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item2\"}]}]",
  "email@email.com",
  "admin@email.com"
);
INSERT INTO `AB_testkcs` (
  `uuid`,
  `created_at`,
  `updated_at`,
  `properties`,
  `testkcsid`,
  `singlelinetext`,
  `singlelinetextrequired`,
  `longtext`,
  `longtextrequired`,
  `number`,
  `numberrequired`,
  `numberunique`,
  `numberformatdecimalsthousands`,
  `numbervalidation`,
  `date`,
  `daterequired`,
  `datetime`,
  `datetimerequired`,
  `time`,
  `checkbox`,
  `checkboxrequired`,
  `selectlist`,
  `selectlistrequired`,
  `selectlistmultiselect`,
  `selectlistmultiselectrequired`,
  `email`,
  `emailrequired`
)
VALUES (
  UUID(),
  NOW(),
  NOW(),
  "text 2",
  "20",
  "text 2",
  "text 2",
  "longtext 2",
  "longtext 2",
  "211",
  "222",
  "233",
  "21.9",
  "25",
  NOW(),
  NOW(),
  NOW(),
  NOW(),
  NOW(),
  "0",
  "1",
  "item1",
  "item5",
  "[{\"id\":\"item1\",\"text\":\"item1\",\"hex\":\"#F44336\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item1\"}]},{\"id\":\"item2\",\"text\":\"item2\",\"hex\":\"#E91E63\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item2\"}]},{\"id\":\"item3\",\"text\":\"item3\",\"hex\":\"#9C27B0\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item3\"}]},{\"id\":\"item4\",\"text\":\"item4\",\"hex\":\"#673AB7\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item4\"}]},{\"id\":\"item5\",\"text\":\"item5\",\"hex\":\"#3F51B5\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item5\"}]}]",
  "[{\"id\":\"item1\",\"text\":\"item1\",\"hex\":\"#F44336\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item1\"}]},{\"id\":\"item2\",\"text\":\"item2\",\"hex\":\"#E91E63\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item2\"}]},{\"id\":\"item3\",\"text\":\"item3\",\"hex\":\"#9C27B0\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item3\"}]},{\"id\":\"item4\",\"text\":\"item4\",\"hex\":\"#673AB7\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item4\"}]},{\"id\":\"item5\",\"text\":\"item5\",\"hex\":\"#3F51B5\",\"translations\":[{\"language_code\":\"en\",\"text\":\"item5\"}]}]",
  "email2@email.com",
  "admin2@email.com"
);
UNLOCK TABLES;
