SET FOREIGN_KEY_CHECKS = 0;
LOCK TABLES `AB_JOINMN_ROLE_USER_users` WRITE;
TRUNCATE TABLE `AB_JOINMN_ROLE_USER_users`;

INSERT INTO `appbuilder-admin`.`AB_JOINMN_ROLE_USER_users` (`id`, `USER`, `ROLE`) VALUES ('1', 'admin', 'eb4f75ea-c995-4fc6-8bab-0ab2d6552508');

UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS = 1;
