SET FOREIGN_KEY_CHECKS = 0;
LOCK TABLES `AB_JOINMN_ROLE_USER_users` WRITE;
TRUNCATE TABLE `AB_JOINMN_ROLE_USER_users`;

INSERT INTO `appbuilder-admin`.`AB_JOINMN_ROLE_USER_users` (`id`, `USER`, `ROLE`) VALUES ('1', 'admin', '4cb11fa7-3d79-412c-9a03-0ce8d7210cde');

UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS = 1;
