SET FOREIGN_KEY_CHECKS = 0;
LOCK TABLES `AB_testkcs` WRITE;
TRUNCATE TABLE `AB_testkcs`;
UNLOCK TABLES
SET FOREIGN_KEY_CHECKS = 1;

SET FOREIGN_KEY_CHECKS = 0;
LOCK TABLES `AB_testkcs2` WRITE;
TRUNCATE TABLE `AB_testkcs2`;
UNLOCK TABLES
SET FOREIGN_KEY_CHECKS = 1;